-- QUESTION 3
SELECT C.CUS_GENDER AS GENDER, COUNT(C.CUS_GENDER) AS GENDER_COUNT, Q.ORD_AMOUNT AS TOT_ORDER_AMT 
FROM CUSTOMER C,
(SELECT * FROM ORDERS WHERE ORD_AMOUNT>=3000) Q 
WHERE C.CUS_ID = Q.CUS_ID
GROUP BY C.CUS_GENDER;

-- QUESTION 4
SELECT T5.ORD_ID, T5.ORD_AMOUNT, T5.ORD_DATE, T6.PRO_NAME
FROM ORDERS T5,
(SELECT T3.PRO_NAME, T3.PRO_ID, T4.PRICING_ID 
FROM PRODUCT T3,
(SELECT T1.CUS_ID, T2.PRO_ID, T2.PRICING_ID 
FROM ORDERS T1, SUPPLIER_PRICING T2 
WHERE T1.PRICING_ID=T2.PRICING_ID) T4 
WHERE T4.CUS_ID=2 AND T4.PRO_ID=T3.PRO_ID) T6
WHERE T5.CUS_ID=2 AND T5.PRICING_ID=T6.PRICING_ID;

-- QUESTION 5
SELECT COUNT(PRO_ID) AS COUNT_OF_PRODS, SUPP_ID, SUPP_PRICE, PRICING_ID 
FROM SUPPLIER_PRICING GROUP BY SUPP_ID;

-- QUESTION 6
SELECT T3.CAT_ID, T4.CAT_NAME, T3.PRO_NAME, MIN(T3.SUPP_PRICE) FROM CATEGORY T4,
(SELECT T2.PRO_NAME, T1.SUPP_PRICE, T2.CAT_ID FROM SUPPLIER_PRICING T1, PRODUCT T2 
WHERE T1.PRO_ID = T2.PRO_ID) T3
WHERE T3.CAT_ID = T4.CAT_ID;

-- QUESTION 7
(SELECT T3.PRO_NAME, T3.PRO_ID, T4.ORD_DATE 
FROM PRODUCT T3,
(SELECT T1.ORD_DATE, T1.CUS_ID, T2.PRO_ID, T2.PRICING_ID 
FROM ORDERS T1, SUPPLIER_PRICING T2 
WHERE T1.PRICING_ID=T2.PRICING_ID) T4 
WHERE T4.PRO_ID=T3.PRO_ID AND T4.ORD_DATE > '2021-10-05');

-- QUESTION 8
SELECT CUS_NAME, CUS_GENDER FROM CUSTOMER WHERE CUS_NAME LIKE "A%" OR CUS_NAME LIKE "%A" ;



