CREATE DEFINER=`root`@`localhost` PROCEDURE `CUST_RATING`()
BEGIN
SELECT T5.SUPP_ID,T5.ORD_ID, T5.SUPP_NAME, T6.RAT_RATSTARS, 
CASE
    WHEN T6.RAT_RATSTARS = 5 THEN 'EXCELLENT SERVICE'
    WHEN T6.RAT_RATSTARS = 4 THEN 'GOOD SERVICE'
    WHEN T6.RAT_RATSTARS > 2 THEN 'AVERAGE SERVICE'
    ELSE 'POOR SERVICE'
END AS TYPE_OF_SERVICE
FROM RATING T6,  	
(SELECT T4.ORD_ID, T3.SUPP_ID, T3.SUPP_NAME FROM ORDERS T4,
(SELECT T1.SUPP_ID, T1.SUPP_NAME, T2.PRICING_ID FROM SUPPLIER T1 INNER JOIN SUPPLIER_PRICING T2
ON T1.SUPP_ID=T2.SUPP_ID) T3
WHERE T4.PRICING_ID=T3.PRICING_ID) T5
WHERE T6.ORD_ID= T5.ORD_ID;
END